### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/PATH/TO/shapenetcore_v2/taxonomy.json'

### ISSUE THREAD

**Issue by chenzixuan99** [ademiadeniji/lamp#1]
Thank you for selflessly sharing such a wonderful code base!

I am getting the following error when I run the  command `"TF_CPP_MIN_LOG_LEVEL=0 CUDA_VISIBLE_DEVICES=0 TF_XLA_FLAGS=--tf_xla_auto_jit=2 vglrun -d :0.0 python train.py --logdir logs --task pick_shapenet_objects --seed 1 --use_r3m_reward True --device cuda:0 --vidlang_model_device cuda:0 --use_lang_embeddings True --configs front_wrist vlsp --curriculum.objects 'bag,bowl,cap,earphone,faucet,jar,knife,laptop,mug,pot,telephone' --curriculum.num_unique_per_class '-1' --curriculum.num_objects '3' --curriculum.lang_prompt 'prompts/similar_verb_40.txt' --curriculum.synonym_folder prompts/similar_noun --curriculum.num_episodes '20000' --randomize True --expl_intr_scale 0.9 --expl_extr_scale 0.1 --plan2explore True“`

`FileNotFoundError: [Errno 2] No such file or directory: '/PATH/TO/shapenetcore_v2/taxonomy.json'`

But I didn't find where the shapenet series of files are provided. Can you please tell me how to solve this error?

I would appreciate if you can help with some suggestions!

**Comment by amberxie88** [comment]
Hi,

You can download ShapeNet here and change the corresponding path: https://shapenet.org/

For reference, our shapenetcore_v2 repository looks something like this:
- taxonomy.json
- 02691156 (this is the shapenet synset id, described in taxonomy.js)
    - 10155655850468db78d106ce0a280f87
        - images, models, screenshots
     - etc. 
- etc.

You may also need to run convex decomposition to simulate the non-convex shapenet objects using https://github.com/kmammou/v-hacd

Let me know if you have further questions!
